In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\nagat\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\nagat\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\nagat\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\nagat\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\nagat\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\nagat\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install numpy

Requirement already satisfied: numpy in c:\users\nagat\anaconda3\lib\site-packages (2.1.3)
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install yfinance

Requirement already satisfied: yfinance in c:\users\nagat\anaconda3\lib\site-packages (1.1.0)
Requirement already satisfied: pandas>=1.3.0 in c:\users\nagat\anaconda3\lib\site-packages (from yfinance) (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in c:\users\nagat\anaconda3\lib\site-packages (from yfinance) (2.1.3)
Requirement already satisfied: requests>=2.31 in c:\users\nagat\anaconda3\lib\site-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\nagat\anaconda3\lib\site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\nagat\anaconda3\lib\site-packages (from yfinance) (4.3.7)
Requirement already satisfied: pytz>=2022.5 in c:\users\nagat\anaconda3\lib\site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\nagat\anaconda3\lib\site-packages (from yfinance) (2.4.2)
Requirement already satisfied: peewee>=3.16.2 in c:\users\nagat\anaconda3\lib\site-packages (from yfinance) (3.19.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\nagat\anaconda3\lib\site-packages (from yfinance) (4.12.3)
Requirement already satisfied: curl_cffi<0.14,>=0.7 in c:\users\nagat\anaconda3\lib\site-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in c:\users\nagat\anaconda3\lib\site-packages (from yfinance) (5.29.3)
Requirement already satisfied: websockets>=13.0 in c:\users\nagat\anaconda3\lib\site-packages (from yfinance) (16.0)
Requirement already satisfied: cffi>=1.12.0 in c:\users\nagat\anaconda3\lib\site-packages (from curl_cffi<0.14,>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in c:\users\nagat\anaconda3\lib\site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2025.4.26)
Requirement already satisfied: soupsieve>1.2 in c:\users\nagat\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: pycparser in c:\users\nagat\anaconda3\lib\site-packages (from cffi>=1.12.0->curl_cffi<0.14,>=0.7->yfinance) (2.21)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\nagat\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\nagat\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\nagat\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\nagat\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\nagat\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\nagat\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.3.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\nagat\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\nagat\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\nagat\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Note: you may need to restart the kernel to use updated packages.

In [5]:
pip install pyodbc

Requirement already satisfied: pyodbc in c:\users\nagat\anaconda3\lib\site-packages (5.2.0)
Note: you may need to restart the kernel to use updated packages.

In [18]:
import yfinance as yf

In [26]:
sp500_df = yf.download(
    "^GSPC",
    start="2020-01-01",
    end="2026-07-18"
)

[*********************100%***********************]  1 of 1 completed

In [27]:
sp500_df.head()

Price             Close         High          Low         Open      Volume
Ticker            ^GSPC        ^GSPC        ^GSPC        ^GSPC       ^GSPC
Date
2020-01-02  3257.850098  3258.139893  3235.530029  3244.669922  3459930000
2020-01-03  3234.850098  3246.149902  3222.340088  3226.360107  3484700000
2020-01-06  3246.280029  3246.840088  3214.639893  3217.550049  3702460000
2020-01-07  3237.179932  3244.909912  3232.429932  3241.860107  3435910000
2020-01-08  3253.050049  3267.070068  3236.669922  3238.590088  3726840000

In [28]:
print(sp500_df.columns)

MultiIndex([( 'Close', '^GSPC'),
            (  'High', '^GSPC'),
            (   'Low', '^GSPC'),
            (  'Open', '^GSPC'),
            ('Volume', '^GSPC')],
           names=['Price', 'Ticker'])

In [29]:
print(type(sp500_df.columns))

<class 'pandas.core.indexes.multi.MultiIndex'>

In [30]:
sp500_df.columns = sp500_df.columns.get_level_values(0)

In [31]:
print(sp500_df.head())

Price             Close         High          Low         Open      Volume
Date
2020-01-02  3257.850098  3258.139893  3235.530029  3244.669922  3459930000
2020-01-03  3234.850098  3246.149902  3222.340088  3226.360107  3484700000
2020-01-06  3246.280029  3246.840088  3214.639893  3217.550049  3702460000
2020-01-07  3237.179932  3244.909912  3232.429932  3241.860107  3435910000
2020-01-08  3253.050049  3267.070068  3236.669922  3238.590088  3726840000

In [32]:
print(sp500_df.shape)

(1643, 5)

In [37]:
#checking the data types
print(sp500_df.dtypes)

Price
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
dtype: object

In [39]:
#checking the null values
print(sp500_df.isnull().sum())

Price
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [40]:
#checking the duplicate the values 
print(sp500_df.duplicated().sum())

0

In [41]:
print(type(sp500_df.index))
print(sp500_df.index)

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>
DatetimeIndex(['2020-01-02', '2020-01-03', '2020-01-06', '2020-01-07',
               '2020-01-08', '2020-01-09', '2020-01-10', '2020-01-13',
               '2020-01-14', '2020-01-15',
               ...
               '2026-07-06', '2026-07-07', '2026-07-08', '2026-07-09',
               '2026-07-10', '2026-07-13', '2026-07-14', '2026-07-15',
               '2026-07-16', '2026-07-17'],
              dtype='datetime64[ns]', name='Date', length=1643, freq=None)

In [42]:
sp500_df.reset_index(inplace=True)

In [43]:
sp500_df.head()

Price,Date,Close,High,Low,Open,Volume
0,2020-01-02,3257.850098,3258.139893,3235.530029,3244.669922,3459930000
1,2020-01-03,3234.850098,3246.149902,3222.340088,3226.360107,3484700000
2,2020-01-06,3246.280029,3246.840088,3214.639893,3217.550049,3702460000
3,2020-01-07,3237.179932,3244.909912,3232.429932,3241.860107,3435910000
4,2020-01-08,3253.050049,3267.070068,3236.669922,3238.590088,3726840000

In [44]:
print(sp500_df.head())

Price       Date        Close         High          Low         Open  \
0     2020-01-02  3257.850098  3258.139893  3235.530029  3244.669922
1     2020-01-03  3234.850098  3246.149902  3222.340088  3226.360107
2     2020-01-06  3246.280029  3246.840088  3214.639893  3217.550049
3     2020-01-07  3237.179932  3244.909912  3232.429932  3241.860107
4     2020-01-08  3253.050049  3267.070068  3236.669922  3238.590088

Price      Volume
0      3459930000
1      3484700000
2      3702460000
3      3435910000
4      3726840000

In [45]:
sp500_df.columns.name = None

In [47]:
print(sp500_df.head())

        Date        Close         High          Low         Open      Volume
0 2020-01-02  3257.850098  3258.139893  3235.530029  3244.669922  3459930000
1 2020-01-03  3234.850098  3246.149902  3222.340088  3226.360107  3484700000
2 2020-01-06  3246.280029  3246.840088  3214.639893  3217.550049  3702460000
3 2020-01-07  3237.179932  3244.909912  3232.429932  3241.860107  3435910000
4 2020-01-08  3253.050049  3267.070068  3236.669922  3238.590088  3726840000

In [48]:
sp500_df["Ticker"] = "^GSPC"
sp500_df["IndexName"] = "S&P 500"

In [49]:
sp500_df.head()

,Date,Close,High,Low,Open,Volume,Ticker,IndexName
0,2020-01-02,3257.850098,3258.139893,3235.530029,3244.669922,3459930000,^GSPC,S&P 500
1,2020-01-03,3234.850098,3246.149902,3222.340088,3226.360107,3484700000,^GSPC,S&P 500
2,2020-01-06,3246.280029,3246.840088,3214.639893,3217.550049,3702460000,^GSPC,S&P 500
3,2020-01-07,3237.179932,3244.909912,3232.429932,3241.860107,3435910000,^GSPC,S&P 500
4,2020-01-08,3253.050049,3267.070068,3236.669922,3238.590088,3726840000,^GSPC,S&P 500